package me.nd.upgrades.utils;

import java.util.*;
import org.bukkit.block.banner.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.*;
import org.bukkit.*;

public class Banner
{
    private static final HashMap<Character, ItemStack> whiteBanners;
    private static final HashMap<Character, ItemStack> redBanners;
    private static final HashMap<Character, ItemStack> cyanBanners;
    
    private static void buildBanners(final DyeColor cima, final DyeColor base, final Boolean color) {
        final ItemStack bannerA = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaA = (BannerMeta)bannerA.getItemMeta();
        bannerMetaA.setBaseColor(cima);
        bannerMetaA.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaA.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaA.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaA.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMetaA.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaA.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerA.setItemMeta((ItemMeta)bannerMetaA);
        final ItemStack bannerB = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaB = (BannerMeta)bannerB.getItemMeta();
        bannerMetaB.setBaseColor(cima);
        bannerMetaB.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaB.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaB.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaB.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaB.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMetaB.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaB.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerB.setItemMeta((ItemMeta)bannerMetaB);
        final ItemStack bannerC = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaC = (BannerMeta)bannerC.getItemMeta();
        bannerMetaC.setBaseColor(cima);
        bannerMetaC.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaC.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaC.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaC.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaC.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerC.setItemMeta((ItemMeta)bannerMetaC);
        final ItemStack bannerD = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaD = (BannerMeta)bannerD.getItemMeta();
        bannerMetaD.setBaseColor(cima);
        bannerMetaD.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaD.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaD.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaD.addPattern(new Pattern(cima, PatternType.CURLY_BORDER));
        bannerMetaD.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaD.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaD.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerD.setItemMeta((ItemMeta)bannerMetaD);
        final ItemStack bannerE = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaE = (BannerMeta)bannerE.getItemMeta();
        bannerMetaE.setBaseColor(cima);
        bannerMetaE.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMetaE.addPattern(new Pattern(cima, PatternType.STRIPE_RIGHT));
        bannerMetaE.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaE.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaE.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaE.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaE.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerE.setItemMeta((ItemMeta)bannerMetaE);
        final ItemStack bannerF = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaF = (BannerMeta)bannerF.getItemMeta();
        bannerMetaF.setBaseColor(cima);
        bannerMetaF.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMetaF.addPattern(new Pattern(cima, PatternType.STRIPE_RIGHT));
        bannerMetaF.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaF.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaF.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaF.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerF.setItemMeta((ItemMeta)bannerMetaF);
        final ItemStack bannerG = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaG = (BannerMeta)bannerG.getItemMeta();
        bannerMetaG.setBaseColor(cima);
        bannerMetaG.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaG.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL));
        bannerMetaG.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaG.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaG.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaG.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaG.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerG.setItemMeta((ItemMeta)bannerMetaG);
        final ItemStack bannerH = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaH = (BannerMeta)bannerH.getItemMeta();
        bannerMetaH.setBaseColor(cima);
        bannerMetaH.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMetaH.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaH.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaH.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaH.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerH.setItemMeta((ItemMeta)bannerMetaH);
        final ItemStack bannerI = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaI = (BannerMeta)bannerI.getItemMeta();
        bannerMetaI.setBaseColor(cima);
        bannerMetaI.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaI.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaI.addPattern(new Pattern(base, PatternType.STRIPE_CENTER));
        bannerMetaI.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaI.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerI.setItemMeta((ItemMeta)bannerMetaI);
        final ItemStack bannerJ = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaJ = (BannerMeta)bannerJ.getItemMeta();
        bannerMetaJ.setBaseColor(cima);
        bannerMetaJ.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaJ.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL));
        bannerMetaJ.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaJ.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaJ.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaJ.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerJ.setItemMeta((ItemMeta)bannerMetaJ);
        final ItemStack bannerK = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaK = (BannerMeta)bannerK.getItemMeta();
        bannerMetaK.setBaseColor(cima);
        bannerMetaK.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaK.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaK.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMetaK.addPattern(new Pattern(cima, PatternType.HALF_VERTICAL_MIRROR));
        bannerMetaK.addPattern(new Pattern(base, PatternType.CROSS));
        bannerMetaK.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaK.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerK.setItemMeta((ItemMeta)bannerMetaK);
        final ItemStack bannerL = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaL = (BannerMeta)bannerL.getItemMeta();
        bannerMetaL.setBaseColor(cima);
        bannerMetaL.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaL.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaL.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaL.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerL.setItemMeta((ItemMeta)bannerMetaL);
        final ItemStack bannerM = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaM = (BannerMeta)bannerM.getItemMeta();
        bannerMetaM.setBaseColor(cima);
        bannerMetaM.addPattern(new Pattern(base, PatternType.TRIANGLE_TOP));
        bannerMetaM.addPattern(new Pattern(cima, PatternType.TRIANGLES_TOP));
        bannerMetaM.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaM.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaM.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaM.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerM.setItemMeta((ItemMeta)bannerMetaM);
        final ItemStack bannerN = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaN = (BannerMeta)bannerN.getItemMeta();
        bannerMetaN.setBaseColor(cima);
        bannerMetaN.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaN.addPattern(new Pattern(cima, PatternType.DIAGONAL_RIGHT_MIRROR));
        bannerMetaN.addPattern(new Pattern(base, PatternType.STRIPE_DOWNRIGHT));
        bannerMetaN.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaN.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaN.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerN.setItemMeta((ItemMeta)bannerMetaN);
        final ItemStack bannerO = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaO = (BannerMeta)bannerO.getItemMeta();
        bannerMetaO.setBaseColor(cima);
        bannerMetaO.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaO.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaO.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaO.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaO.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaO.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerO.setItemMeta((ItemMeta)bannerMetaO);
        final ItemStack bannerP = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaP = (BannerMeta)bannerP.getItemMeta();
        bannerMetaP.setBaseColor(base);
        bannerMetaP.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL));
        bannerMetaP.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaP.addPattern(new Pattern(cima, PatternType.STRIPE_BOTTOM));
        bannerMetaP.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaP.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaP.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaP.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerP.setItemMeta((ItemMeta)bannerMetaP);
        final ItemStack bannerQ = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaQ = (BannerMeta)bannerQ.getItemMeta();
        bannerMetaQ.setBaseColor(cima);
        bannerMetaQ.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaQ.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaQ.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaQ.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaQ.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaQ.addPattern(new Pattern(base, PatternType.SQUARE_BOTTOM_RIGHT));
        bannerMetaQ.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerQ.setItemMeta((ItemMeta)bannerMetaQ);
        final ItemStack bannerR = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaR = (BannerMeta)bannerR.getItemMeta();
        bannerMetaR.setBaseColor(cima);
        bannerMetaR.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaR.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaR.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL_MIRROR));
        bannerMetaR.addPattern(new Pattern(base, PatternType.STRIPE_DOWNRIGHT));
        bannerMetaR.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaR.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaR.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerR.setItemMeta((ItemMeta)bannerMetaR);
        final ItemStack bannerS = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaS = (BannerMeta)bannerS.getItemMeta();
        bannerMetaS.setBaseColor(cima);
        bannerMetaS.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaS.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaS.addPattern(new Pattern(cima, PatternType.RHOMBUS_MIDDLE));
        bannerMetaS.addPattern(new Pattern(base, PatternType.STRIPE_DOWNRIGHT));
        bannerMetaS.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaS.addPattern(new Pattern(cima, PatternType.CURLY_BORDER));
        bannerMetaS.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerS.setItemMeta((ItemMeta)bannerMetaS);
        final ItemStack bannerT = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaT = (BannerMeta)bannerT.getItemMeta();
        bannerMetaT.setBaseColor(cima);
        bannerMetaT.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaT.addPattern(new Pattern(base, PatternType.STRIPE_CENTER));
        bannerMetaT.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaT.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerT.setItemMeta((ItemMeta)bannerMetaT);
        final ItemStack bannerU = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaU = (BannerMeta)bannerU.getItemMeta();
        bannerMetaU.setBaseColor(cima);
        bannerMetaU.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaU.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaU.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaU.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaU.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerU.setItemMeta((ItemMeta)bannerMetaU);
        final ItemStack bannerV = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaV = (BannerMeta)bannerV.getItemMeta();
        bannerMetaV.setBaseColor(cima);
        bannerMetaV.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaV.addPattern(new Pattern(cima, PatternType.TRIANGLES_BOTTOM));
        bannerMetaV.addPattern(new Pattern(base, PatternType.STRIPE_DOWNLEFT));
        bannerMetaV.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaV.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerV.setItemMeta((ItemMeta)bannerMetaV);
        final ItemStack bannerW = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaW = (BannerMeta)bannerW.getItemMeta();
        bannerMetaW.setBaseColor(cima);
        bannerMetaW.addPattern(new Pattern(base, PatternType.TRIANGLE_BOTTOM));
        bannerMetaW.addPattern(new Pattern(cima, PatternType.TRIANGLES_BOTTOM));
        bannerMetaW.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMetaW.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMetaW.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaW.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerW.setItemMeta((ItemMeta)bannerMetaW);
        final ItemStack bannerX = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaX = (BannerMeta)bannerX.getItemMeta();
        bannerMetaX.setBaseColor(cima);
        bannerMetaX.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaX.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaX.addPattern(new Pattern(cima, PatternType.STRIPE_CENTER));
        bannerMetaX.addPattern(new Pattern(base, PatternType.CROSS));
        bannerMetaX.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaX.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerX.setItemMeta((ItemMeta)bannerMetaX);
        final ItemStack bannerY = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaY = (BannerMeta)bannerY.getItemMeta();
        bannerMetaY.setBaseColor(cima);
        bannerMetaY.addPattern(new Pattern(base, PatternType.CROSS));
        bannerMetaY.addPattern(new Pattern(cima, PatternType.HALF_VERTICAL_MIRROR));
        bannerMetaY.addPattern(new Pattern(base, PatternType.STRIPE_DOWNLEFT));
        bannerMetaY.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaY.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerY.setItemMeta((ItemMeta)bannerMetaY);
        final ItemStack bannerZ = new ItemStack(Material.BANNER);
        final BannerMeta bannerMetaZ = (BannerMeta)bannerZ.getItemMeta();
        bannerMetaZ.setBaseColor(cima);
        bannerMetaZ.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMetaZ.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMetaZ.addPattern(new Pattern(base, PatternType.STRIPE_DOWNLEFT));
        bannerMetaZ.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMetaZ.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        bannerZ.setItemMeta((ItemMeta)bannerMetaZ);
        final ItemStack banner1 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta1 = (BannerMeta)banner1.getItemMeta();
        bannerMeta1.setBaseColor(cima);
        bannerMeta1.addPattern(new Pattern(base, PatternType.SQUARE_TOP_LEFT));
        bannerMeta1.addPattern(new Pattern(base, PatternType.STRIPE_CENTER));
        bannerMeta1.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta1.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta1.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner1.setItemMeta((ItemMeta)bannerMeta1);
        final ItemStack banner2 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta2 = (BannerMeta)banner2.getItemMeta();
        bannerMeta2.setBaseColor(cima);
        bannerMeta2.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta2.addPattern(new Pattern(cima, PatternType.RHOMBUS_MIDDLE));
        bannerMeta2.addPattern(new Pattern(base, PatternType.STRIPE_DOWNLEFT));
        bannerMeta2.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta2.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta2.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner2.setItemMeta((ItemMeta)bannerMeta2);
        final ItemStack banner3 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta3 = (BannerMeta)banner3.getItemMeta();
        bannerMeta3.setBaseColor(cima);
        bannerMeta3.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMeta3.addPattern(new Pattern(cima, PatternType.STRIPE_LEFT));
        bannerMeta3.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta3.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMeta3.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta3.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta3.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner3.setItemMeta((ItemMeta)bannerMeta3);
        final ItemStack banner4 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta4 = (BannerMeta)banner4.getItemMeta();
        bannerMeta4.setBaseColor(base);
        bannerMeta4.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL));
        bannerMeta4.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMeta4.addPattern(new Pattern(cima, PatternType.STRIPE_BOTTOM));
        bannerMeta4.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMeta4.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMeta4.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta4.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner4.setItemMeta((ItemMeta)bannerMeta4);
        final ItemStack banner5 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta5 = (BannerMeta)banner5.getItemMeta();
        bannerMeta5.setBaseColor(cima);
        bannerMeta5.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta5.addPattern(new Pattern(base, PatternType.STRIPE_DOWNRIGHT));
        bannerMeta5.addPattern(new Pattern(cima, PatternType.CURLY_BORDER));
        bannerMeta5.addPattern(new Pattern(base, PatternType.SQUARE_BOTTOM_LEFT));
        bannerMeta5.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta5.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta5.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner5.setItemMeta((ItemMeta)bannerMeta5);
        final ItemStack banner6 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta6 = (BannerMeta)banner6.getItemMeta();
        bannerMeta6.setBaseColor(cima);
        bannerMeta6.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMeta6.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL));
        bannerMeta6.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta6.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMeta6.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMeta6.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta6.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta6.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner6.setItemMeta((ItemMeta)bannerMeta6);
        final ItemStack banner7 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta7 = (BannerMeta)banner7.getItemMeta();
        bannerMeta7.setBaseColor(cima);
        bannerMeta7.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta7.addPattern(new Pattern(cima, PatternType.DIAGONAL_RIGHT));
        bannerMeta7.addPattern(new Pattern(base, PatternType.STRIPE_DOWNLEFT));
        bannerMeta7.addPattern(new Pattern(base, PatternType.SQUARE_BOTTOM_LEFT));
        bannerMeta7.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta7.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner7.setItemMeta((ItemMeta)bannerMeta7);
        final ItemStack banner8 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta8 = (BannerMeta)banner8.getItemMeta();
        bannerMeta8.setBaseColor(cima);
        bannerMeta8.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMeta8.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta8.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMeta8.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta8.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMeta8.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta8.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner8.setItemMeta((ItemMeta)bannerMeta8);
        final ItemStack banner9 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta9 = (BannerMeta)banner9.getItemMeta();
        bannerMeta9.setBaseColor(cima);
        bannerMeta9.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMeta9.addPattern(new Pattern(cima, PatternType.HALF_HORIZONTAL_MIRROR));
        bannerMeta9.addPattern(new Pattern(base, PatternType.STRIPE_MIDDLE));
        bannerMeta9.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta9.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMeta9.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta9.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner9.setItemMeta((ItemMeta)bannerMeta9);
        final ItemStack banner10 = new ItemStack(Material.BANNER);
        final BannerMeta bannerMeta10 = (BannerMeta)banner10.getItemMeta();
        bannerMeta10.setBaseColor(cima);
        bannerMeta10.addPattern(new Pattern(base, PatternType.STRIPE_TOP));
        bannerMeta10.addPattern(new Pattern(base, PatternType.STRIPE_RIGHT));
        bannerMeta10.addPattern(new Pattern(base, PatternType.STRIPE_BOTTOM));
        bannerMeta10.addPattern(new Pattern(base, PatternType.STRIPE_LEFT));
        bannerMeta10.addPattern(new Pattern(base, PatternType.STRIPE_DOWNLEFT));
        bannerMeta10.addPattern(new Pattern(cima, PatternType.BORDER));
        bannerMeta10.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_POTION_EFFECTS });
        banner10.setItemMeta((ItemMeta)bannerMeta10);
        HashMap<Character, ItemStack> map;
        if (color == null) {
            map = Banner.cyanBanners;
        }
        else if (color) {
            map = Banner.redBanners;
        }
        else {
            map = Banner.whiteBanners;
        }
        map.put('A', bannerA);
        map.put('B', bannerB);
        map.put('C', bannerC);
        map.put('D', bannerD);
        map.put('E', bannerE);
        map.put('F', bannerF);
        map.put('G', bannerG);
        map.put('H', bannerH);
        map.put('I', bannerI);
        map.put('J', bannerJ);
        map.put('K', bannerK);
        map.put('L', bannerL);
        map.put('M', bannerM);
        map.put('N', bannerN);
        map.put('O', bannerO);
        map.put('P', bannerP);
        map.put('Q', bannerQ);
        map.put('R', bannerR);
        map.put('S', bannerS);
        map.put('T', bannerT);
        map.put('U', bannerU);
        map.put('V', bannerV);
        map.put('W', bannerW);
        map.put('X', bannerX);
        map.put('Y', bannerY);
        map.put('Z', bannerZ);
        map.put('0', banner10);
        map.put('1', banner1);
        map.put('2', banner2);
        map.put('3', banner3);
        map.put('4', banner4);
        map.put('5', banner5);
        map.put('6', banner6);
        map.put('7', banner7);
        map.put('8', banner8);
        map.put('9', banner9);
    }
    
    public static ItemStack getWhiteBanner(final String string) {
        final Character c = ChatColor.stripColor(string.toUpperCase()).substring(0, 1).charAt(0);
        return Banner.whiteBanners.get(c);
    }
    
    public static ItemStack getRedBanner(final String string) {
        final Character c = ChatColor.stripColor(string.toUpperCase()).substring(0, 1).charAt(0);
        return Banner.redBanners.get(c);
    }
    
    public static ItemStack getCyanBanner(final String string) {
        final Character c = ChatColor.stripColor(string.toUpperCase()).substring(0, 1).charAt(0);
        return Banner.cyanBanners.get(c);
    }
    
    static {
        whiteBanners = new HashMap<Character, ItemStack>();
        redBanners = new HashMap<Character, ItemStack>();
        cyanBanners = new HashMap<Character, ItemStack>();
        buildBanners(DyeColor.WHITE, DyeColor.BLACK, false);
        buildBanners(DyeColor.ORANGE, DyeColor.BLACK, true);
        buildBanners(DyeColor.CYAN, DyeColor.BLACK, null);
    }
}
